base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view , name='login'),
    path('base/', views.base , name='base'),

    path('tracker/',views.tracker,name='tracker'),
    path('items/',views.items,name='items'),
    path('search/',views.search_item,name='search_item'),

    path('add_transporter/', views.add_transporter,name='add_transporter'),
    path('add_transporter_save/', views.add_transporter_save,name='add_transporter_save'),
    path('add_item/', views.add_item,name='add_item'),
    path('add_item_save/', views.add_item_save,name='add_item_save'),

    path('add_order/', views.add_order,name='add_order'),
    path('add_order_save/', views.add_order_save,name='add_order_save'),

    path('tracker/', views.tracker, name="tracker"),


    path('tracking/', views.tracker, name="tracker"),

    path('check_email_exist/', views.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', views.check_username_exist, name="check_username_exist"),
    path('', views.loginPage, name="login"),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),

]

electronic_tracking/urls.py
from django.contrib import admin
from django.urls import path, include
from base import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls")),
]

base/models.py
# from click import Group
from django.db import models
import uuid
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
# Create your models here.




class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        return self.create_user(email, username, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
   




class Item(models.Model):
    item_name = models.CharField(max_length=100)
    specification = models.TextField()
    item_id = models.IntegerField(null=True, blank=True,unique=True)
    objects = models.Manager()
    unique_code = models.CharField(max_length=32, unique=True,default=0)

    def save(self, *args, **kwargs):
        if not self.unique_code:
            self.unique_code = uuid.uuid4().hex[:8] 
        super().save(*args, **kwargs)
    

    def __str__(self):
        return self.item_name

class Transporter(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    phone_number = models.IntegerField(default=0)
    address = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 
    objects = models.Manager()

    
class Order(models.Model):
    id = models.AutoField(primary_key=True)
    item_id = models.ForeignKey(Item, on_delete= models.CASCADE, default=1)
    destination = models.CharField(max_length=100)
    transporter_id = models.ForeignKey(CustomUser, on_delete= models.CASCADE, default=1)
    receiver_first_name = models.CharField(max_length=255)
    receiver_last_name = models.CharField(max_length=255)
    receiver_id_number = models.IntegerField(default=0)
    receiver_confirmation = models.BooleanField(default=False, null=True)
    objects = models.Manager()
    
    
@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    # if Created is true (Means Data Inserted)
    if created: 
        Transporter.objects.create(user=instance)
@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    instance.transporter.save()
           

base/forms.py
from django import forms

class ItemSearchForm(forms.Form):
    unique_code = forms.CharField(label='Enter Unique Code')

base/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from .forms import ItemSearchForm

from django.views.decorators.csrf import csrf_exempt

from .models import Item,Transporter,CustomUser,Order
from base.EmailBackEnd import EmailBackEnd


# Create your views here.

def loginPage(request):
       return render(request,'login.html')
def doLogin(request):
    if request.method != "POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        user = EmailBackEnd.authenticate(request, username=request.POST.get('email'), password=request.POST.get('password'))
        if user != None:
            login(request, user)
            #return HttpResponse("Email: "+request.POST.get('email')+ " Password: "+request.POST.get('password'))
            return redirect('base')
        else:
            messages.error(request, "Invalid Login Credentials!")
            #return HttpResponseRedirect("/")
            return redirect('login')
def get_user_details(request):
    if request.user != None:
        return HttpResponse("User: "+request.user.email+" Username: "+request.user.username)
    else:
        return HttpResponse("Please Login First")

def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')

def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        user = authenticate(request, email=email, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('base.html')  
        else:
            messages.error(request, 'Invalid username or password.')
    
    return render(request, 'login.html')




def base(request):
    return render(request,'base.html')  

def search_item(request):
    if request.method == 'POST':
        unique_code = request.POST.get('unique_code')
        items = Item.objects.filter(unique_code=unique_code)
        return render(request, 'search_results.html', {'items': items})
    return render(request, 'search_form.html')
    
def tracker(request):
        # will display all orders and their status
        orders = Order.objects.all()
        
        
        context = {
                'orders': orders
        } 
        
        
        return render(request,'base/tracking.html',context) 

def add_item(request):
        return render(request,'base/add_item.html') 

def add_item_save(request):
        if request.method != 'POST':
                messages.error(request, 'Invalid Method')
                return redirect('add_item')
        else:
                item_name = request.POST.get('item_name')
                specification = request.POST.get('specification')
                item_id = request.POST.get('item_id')
        try:
                add_item = Item(item_name=item_name,specification=specification,item_id=item_id)
                add_item.save()
                messages.success(request, "Item Added.")
                return redirect('add_item')
        except Exception as e:
                print(e)
                messages.error(request, "Failed to Add Item.")
                return redirect('add_item')


def items(request):
        # will display all items
        items = Item.objects.all()
        
        
        context = {
                'items': items
        } 
        
        
        return render(request,'base/items.html',context) 
        
def add_transporter(request):
        return render(request,'base/add_transporter.html')        
def add_transporter_save(request):
        if request.method != "POST":
                messages.error(request, "Invalid Method ")
                return redirect('add_transporter')
        else:
                first_name = request.POST.get('first_name')
                last_name = request.POST.get('last_name')
                username = request.POST.get('username')
                email = request.POST.get('email')
                password = request.POST.get('password')
                address = request.POST.get('address')
                phone_number = request.POST.get('phone_number')
                

        try:
                transporter = Transporter.objects.all()
                user = CustomUser.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
                user.transporter.phone_number = phone_number
                user.transporter.address = address
                user.save()
            
                messages.success(request, "Transporter Added Successfully!")
                return redirect('add_transporter')
        except Exception as e:
            print(e)
            messages.error(request, "Failed to Add transporter!")
            return redirect('add_transporter')
    
def add_order(request): 
        transporters = Transporter.objects.all()

        items = Item.objects.all()
        context = {
                'transporters': transporters,
                'items': items,
        }    
        return render(request,'base/add_order.html',context)

def add_order_save(request):
        transporters = Transporter.objects.all()
        items = Item.objects.all()
        context = {
                'transporters': transporters,
                'items': items,
        }
        if request.method != 'POST':
                messages.error(request, 'Invalid Method')
                return redirect('add_order')
        else:
                item_id= request.POST.get('item_name')
                item = Item.objects.get(id=item_id)

                destination = request.POST.get('destination')
                transporter_id = request.POST.get('transporter')
                transporter = CustomUser.objects.get(id=transporter_id)

                receiver_first_name = request.POST.get('receiver_first_name')
                receiver_last_name = request.POST.get('receiver_last_name')
                receiver_id_number = request.POST.get('receiver_id_number')
                receiver_confirmation = request.POST.get('receiver_confirmation')
        try:
                add_order = Order(item_id=item,destination=destination,transporter_id=transporter,
                                  receiver_first_name=receiver_first_name,receiver_last_name=receiver_last_name
                                  ,receiver_id_number=receiver_id_number,receiver_confirmation=receiver_confirmation)
                
                add_order.save()
                messages.success(request, "Order Added.")
                return redirect('add_order')
        except Exception as e:
                print(e)
                messages.error(request, "Failed to Add Order.")
                return redirect('add_order')

         
@csrf_exempt
def check_email_exist(request):
    email = request.POST.get("email")
    user_obj = CustomUser.objects.filter(email=email).exists()
    if user_obj:
        return HttpResponse(True)
    else:
        return HttpResponse(False)


@csrf_exempt
def check_username_exist(request):
    username = request.POST.get("username")
    user_obj = CustomUser.objects.filter(username=username).exists()
    if user_obj:
        return HttpResponse(True)
    else:
        return HttpResponse(False)

base/templates/base/add_item.html
{% extends 'base.html' %}

{% block page_title %}
    Add Item
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Add Item</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{% url 'add_item_save' %}">
                        {% csrf_token %}

                        
                                {% comment %} Display Messages {% endcomment %}
                                {% if messages %}
                                <div class="form-group">
                                <div class="col-12">
                                    {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                </div>
                                {% endif %}
                            

                        <div class="card-body">

                            <div class="form-group">
                                <label>Item Name</label>
                                <input type="text" class="form-control" name="item_name" placeholder="Item Name" id="id_item_name">
                            </div>
                            <div class="form-group">
                              <label for="specification">Specification</label>
                              <textarea class="form-control" name="specification" id="" rows="3"></textarea>
                            </div>

                            <div class="form-group">
                                <label>Item Id</label>
                                <input type="text" class="form-control" name="item_id" placeholder="Item Id">
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Add Item</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

base/templates/base/add_order.html
{% extends 'base.html' %}

{% block page_title %}
    Add Order
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Add Order</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{% url 'add_order_save' %}">
                        {% csrf_token %}

                        
                                {% comment %} Display Messages {% endcomment %}
                                {% if messages %}
                                <div class="form-group">
                                <div class="col-12">
                                    {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                </div>
                                {% endif %}
                            

                        <div class="card-body">
                            <div class="form-group">
                                <label>Item </label>
                                <select class="form-control" name="item_name">
                                    {% for item in items %}
                                        <option value="{{ item.id }}">{{ item.item_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            
                            <div class="form-group">
                                <label>Destination </label>
                                <input type="text" class="form-control" name="destination" placeholder="Destination">
                            </div>
                            <div class="form-group">
                                <label>Receiver Id Number</label>
                                <input type="text" class="form-control" name="receiver_id_number" placeholder="Receiver Id Number">
                            </div>
                            <div class="form-group">
                                <label>Receiver First Name </label>
                                <input type="text" class="form-control" name="receiver_first_name" placeholder="First Name">
                            </div>
                            <div class="form-group">
                                <label>Receiver Last Name</label>
                                <input type="text" class="form-control" name="receiver_last_name" placeholder="Receiver Last Name">
                            </div>
                        

                             <div class="form-group">
                                <label>Transporter</label>
                                <select class="form-control" name="transporter">
                                    {% for transporter in transporters %}
                                        <option value="{{ transporter.id }}">{{ transporter.user.first_name }} {{ transporter.user.last_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit"  class="btn btn-primary">Add Order</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

base/templates/base/add_transporter.html
{% extends 'base.html' %}

{% block page_title %}
    Add Transporter
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Add Transporter</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{% url 'add_transporter_save' %}">
                        {% csrf_token %}

                        
                                {% comment %} Display Messages {% endcomment %}
                                {% if messages %}
                                <div class="form-group">
                                <div class="col-12">
                                    {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                </div>
                                {% endif %}
                            

                        <div class="card-body">
                            <div class="form-group">
                                <label>Email address</label>
                                <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email">
                            </div>

                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" class="form-control" name="username" placeholder="Username" id="id_username">
                            </div>

                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" name="password" placeholder="Password">
                            </div>

                            <div class="form-group">
                                <label>First Name</label>
                                <input type="text" class="form-control" name="first_name" placeholder="First Name">
                            </div>

                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" name="last_name" placeholder="Last Name">
                            </div>

                            <div class="form-group">
                                <label>Address</label>
                                <textarea class="form-control" name="address" placeholder="Address"></textarea>
                            </div>
                            <div class="form-group">
                                <label>Phone Number</label>
                                <input type="text" class="form-control" name="phone_number" placeholder="Phone Number">
                            </div>
                            

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Add Transporter</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

    {% block custom_js %}
    {% comment %} Checking if email and username already exists or not usin Ajax {% endcomment %}

    <script>
        $(document).ready(function(){
            // keyup event will be triggered when user leaves keyboard
            $("#id_email").keyup(function(){
                var email = $(this).val();

                if(email!=""){
                    $.ajax({
                        url : '{% url 'check_email_exist' %}',
                        type : 'POST',
                        data : {email:email}
                    })
                    .done(function(response){
                        //console.log(response);

                        if(response == "True"){
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: red; padding: 5px; font-weight: bold;'> Email Not Available. </span>").insertAfter("#id_email")
                        }
                        else{
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: green; padding: 5px; font-weight: bold;'> Email Available. </span>").insertAfter("#id_email")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".email_error").remove();
                }
                
            })

            $("#id_username").keyup(function(){
                var username = $(this).val();
                
                if(username!=""){
                    $.ajax({
                        url : '{% url 'check_username_exist' %}',
                        type : 'POST',
                        data : {username:username}
                    })
                    .done(function(response){
                        //console.log(response);

                        if(response == "True"){
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: red; padding: 5px; font-weight: bold;'> Username Not Available. </span>").insertAfter("#id_username")
                        }
                        else{
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: green; padding: 5px; font-weight: bold;'> Username Available. </span>").insertAfter("#id_username")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".username_error").remove();
                }
                
            })
        })
    </script>

  {% endblock custom_js %}

base/templates/base/items.html
{% extends 'base.html' %}

{% block page_title %}
    ITEMS
{% endblock page_title %}

{% block main_content %}

{% load static %}

    <div class="jumbotron2">
       <form action="" method="post" class="container">
        <table class="table table-dark">
            <thead class="thead-light">
                <tr>
                    <th>Unique Code</th>
                    <th>Item name</th>
                    <th>Item ID </th>
                    <th>Specifications</th>
                    <th>Actions</th>
                    
    
                </tr>
            </thead>
            {% for item in items %}
            <tbody>
                    <tr>
                        <td>
                            {{ item.unique_code }}
                        </td>
                        <td>
                            {{ item.item_name }}
                        </td>
                        <td>
                            {{ item.item_id }}
                        </td>
                        <td>
                            {{ item.specification }}
                        </td>
                       
                        <td>
                            <div class="row ">
                                <button type="button" name="" id="" class="btn btn-danger btn-lg btn-block col m-2 p-0">
                                    <i class="fas fa-print"></i>Update
                                </button>
                                <button type="button" class="btn btn-danger col m-2 p-0">
                                    <i class="fas fa-print"></i>Print
                                </button>
                            </div>
                        </td>
                        
                    </tr>
                </tbody>
            {% endfor %}
                
           
            
        </table>
       </form>
    </div>
    <div class="text ">
        

    </div>
    
    




{% endblock main_content %}